[project]
name = "sentry"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.12.14",
    "openai>=1.90.0",
    "scrapy>=2.13.3",
    "wikipedia>=1.4.0",
]
